//! Bragi property identifiers.
//!
//! Every readable/writable property on a Bragi device is addressed by a
//! 16-bit [`PropertyId`]. The enum below covers all known IDs.

/// Numeric property identifier used in Bragi read/write transactions.
///
/// Each variant maps to a `u16` wire value. Use [`PropertyId::from_u16`]
/// to decode a raw value received from the device.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[repr(u16)]
pub enum PropertyId {
    Invalid = 0,
    PollingRate = 1,
    Brightness = 2,
    OperatingMode = 3,
    DebugMode = 4,
    LiftHeight = 6,
    AngleSnappingEnabled = 7,
    AngleSnappingAngle = 8,
    ButtonPressDebounceHackEnabled = 9,
    ButtonPressDebounceHackTimeout = 10,
    PowerSavingModeEnabled = 11,
    PowerSavingModeFeatures = 12,
    AutomaticSleepEnabled = 13,
    AutomaticSleepTimeoutNormal = 14,
    BatteryLevel = 15,
    BatteryStatus = 16,
    UsbVid = 17,
    UsbPid = 18,
    FirmwareVersion = 19,
    BootloaderVersion = 20,
    WirelessChipFirmwareVersion = 21,
    WirelessChipBootloaderVersion = 22,
    RfPower = 23,
    StoredMouseSensorResolutionStage1 = 24,
    StoredMouseSensorResolutionStage2 = 25,
    StoredMouseSensorResolutionStage3 = 26,
    StoredMouseSensorResolutionStage4 = 27,
    StoredMouseSensorResolutionStage5 = 28,
    StoredMouseSensorResolutionStageSniper = 29,
    CurrentStoredMouseSensorResolutionStageIndex = 30,
    EnabledStoredMouseSensorResolutionStages = 31,
    MouseSensorResolution = 32,
    MouseSensorResolutionX = 33,
    MouseSensorResolutionY = 34,
    StoredMouseSensorResolutionStage1X = 35,
    StoredMouseSensorResolutionStage1Y = 36,
    StoredMouseSensorResolutionStage2X = 37,
    StoredMouseSensorResolutionStage2Y = 38,
    StoredMouseSensorResolutionStage3X = 39,
    StoredMouseSensorResolutionStage3Y = 40,
    StoredMouseSensorResolutionStage4X = 41,
    StoredMouseSensorResolutionStage4Y = 42,
    StoredMouseSensorResolutionStage5X = 43,
    StoredMouseSensorResolutionStage5Y = 44,
    StoredMouseSensorResolutionStageSniperX = 45,
    StoredMouseSensorResolutionStageSniperY = 46,
    StoredMouseSensorResolutionStageColor1 = 47,
    StoredMouseSensorResolutionStageColor2 = 48,
    StoredMouseSensorResolutionStageColor3 = 49,
    StoredMouseSensorResolutionStageColor4 = 50,
    StoredMouseSensorResolutionStageColor5 = 51,
    StoredMouseSensorResolutionStageColorSniper = 52,
    WirelessModeSwitchPosition = 53,
    ConnectedSubdevicesBitmap = 54,
    AutomaticSleepTimeoutPowersave = 55,
    ButtonReleaseDebounceHackTimeout = 56,
    ButtonReleaseDebounceHackEnabled = 57,
    WirelessMode = 58,
    SurfaceCalibrationPresetMode = 59,
    SurfaceCalibrationPresetIndex = 60,
    TotalStorageSize = 61,
    FreeStorageSize = 62,
    MaximumBrightnessLimitEnabled = 63,
    IdleTime = 64,
    PhysicalKeyboardLayout = 65,
    BrightnessLevelIndex = 68,
    WinLockEnabled = 69,
    SidetoneMuted = 70,
    SidetoneLevel = 71,
    ProfileIndicatorColor = 73,
    WinLockDisabledShortcuts = 74,
    WirelessEncryptionStatusSubdevice1 = 75,
    HardwareProfile1ActiveMouseSensorResolutionStageIndex = 79,
    HardwareProfile2ActiveMouseSensorResolutionStageIndex = 80,
    HardwareProfile3ActiveMouseSensorResolutionStageIndex = 81,
    AmbidextrousMode = 82,
    CoolerComponentProductLineId = 85,
    CoolerComponentProductVendorId = 86,
    CoolerComponentPumpVersionId = 87,
    CoolerComponentRadiatorSize = 88,
    LedModuleProductLineId = 89,
    LedModuleVendorId = 90,
    LedModuleVersionId = 91,
    BrightnessIndicatorColor = 92,
    WinLockEnabledIndicatorColor = 93,
    WinLockDisabledIndicatorColor = 94,
    WirelessFirmwareVariant = 95,
    DialRingRotation = 96,
    ProfileIndicationBehavior = 98,
    WinLockIndicationBehavior = 99,
    DialModeIndicationBehavior = 100,
    ExceptionalState = 101,
    WirelessEncryptionStatusSubdevice2 = 102,
    WirelessEncryptionStatusSubdevice3 = 103,
    WirelessEncryptionStatusSubdevice4 = 104,
    WirelessEncryptionStatusSubdevice5 = 105,
    WirelessEncryptionStatusSubdevice6 = 106,
    WirelessEncryptionStatusSubdevice7 = 107,
    ActiveDialModeIndex = 108,
    DialZoneBrightness = 109,
    ActiveHardwareProfileIndex = 110,
    WirelessConnectionConfiguration = 115,
    WirelessConnectionConfigurationSupport = 116,
    PrimaryFirmwareStatus = 117,
    EsportsModeSwitchPosition = 118,
    EsportsModeBacklightColor = 119,
    HostOperatingSystem = 120,
    HwDpiAdjustmentEnabled = 121,
    LeftTriggerDeadzone = 122,
    RightTriggerDeadzone = 123,
    LeftThumbstickDeadzone = 124,
    RightThumbstickDeadzone = 125,
    LeftTriggerSensitivity = 126,
    RightTriggerSensitivity = 127,
    LeftThumbstickSensitivity = 128,
    RightThumbstickSensitivity = 129,
    LeftVibrationMotorPresent = 130,
    RightVibrationMotorPresent = 131,
    LeftVibrationMotorIntensity = 132,
    RightVibrationMotorIntensity = 133,
    MicrophoneMuted = 142,
    MicrophoneLevel = 143,
    MaximumPollingRate = 150,
    CapsLockIndicationBehavior = 155,
    ScrollLockIndicationBehavior = 156,
    CapsLockEnabledIndicatorColor = 158,
    ScrollLockEnabledIndicatorColor = 159,
    MacroRecordingIndicatorColor = 161,
    HwMenuFn2SwapFunctionEnabled = 162,
    HardwareProfile4ActiveMouseSensorResolutionStageIndex = 164,
    HardwareProfile5ActiveMouseSensorResolutionStageIndex = 165,
    MicrophoneMuteSwitchPosition = 166,
    GyroscopeReportingMode = 168,
    ButtonDebounceAlgorithm = 176,
    BrightnessIndicationBehavior = 177,
    HardwareActionFeatures = 180,
    TiltForwardGestureTriggerAngle = 183,
    TiltBackwardGestureTriggerAngle = 184,
    TiltLeftGestureTriggerAngle = 185,
    TiltRightGestureTriggerAngle = 186,
    TiltForwardGestureEnabled = 187,
    TiltBackwardGestureEnabled = 188,
    TiltLeftGestureEnabled = 189,
    TiltRightGestureEnabled = 190,
    MultipleGesturesPerMovementEnabled = 191,
    TriggerPositionsReportingEnabled = 192,
    ThumbstickPositionsReportingEnabled = 193,
    AutomaticBrightnessAdjustmentEnabled = 196,
    AutomaticBrightnessOverrideActive = 197,
    AnalogWASDReportingMode = 198,
    AnalogArrowsReportingMode = 199,
    SubdevicesDetectionWarnings = 206,
}

impl PropertyId {
    /// Decode a raw `u16` wire value into a known property, returning `None`
    /// for unrecognized IDs.
    #[must_use]
    pub const fn from_u16(val: u16) -> Option<Self> {
        match val {
            0 => Some(Self::Invalid),
            1 => Some(Self::PollingRate),
            2 => Some(Self::Brightness),
            3 => Some(Self::OperatingMode),
            4 => Some(Self::DebugMode),
            6 => Some(Self::LiftHeight),
            7 => Some(Self::AngleSnappingEnabled),
            8 => Some(Self::AngleSnappingAngle),
            9 => Some(Self::ButtonPressDebounceHackEnabled),
            10 => Some(Self::ButtonPressDebounceHackTimeout),
            11 => Some(Self::PowerSavingModeEnabled),
            12 => Some(Self::PowerSavingModeFeatures),
            13 => Some(Self::AutomaticSleepEnabled),
            14 => Some(Self::AutomaticSleepTimeoutNormal),
            15 => Some(Self::BatteryLevel),
            16 => Some(Self::BatteryStatus),
            17 => Some(Self::UsbVid),
            18 => Some(Self::UsbPid),
            19 => Some(Self::FirmwareVersion),
            20 => Some(Self::BootloaderVersion),
            21 => Some(Self::WirelessChipFirmwareVersion),
            22 => Some(Self::WirelessChipBootloaderVersion),
            23 => Some(Self::RfPower),
            24 => Some(Self::StoredMouseSensorResolutionStage1),
            25 => Some(Self::StoredMouseSensorResolutionStage2),
            26 => Some(Self::StoredMouseSensorResolutionStage3),
            27 => Some(Self::StoredMouseSensorResolutionStage4),
            28 => Some(Self::StoredMouseSensorResolutionStage5),
            29 => Some(Self::StoredMouseSensorResolutionStageSniper),
            30 => Some(Self::CurrentStoredMouseSensorResolutionStageIndex),
            31 => Some(Self::EnabledStoredMouseSensorResolutionStages),
            32 => Some(Self::MouseSensorResolution),
            33 => Some(Self::MouseSensorResolutionX),
            34 => Some(Self::MouseSensorResolutionY),
            35 => Some(Self::StoredMouseSensorResolutionStage1X),
            36 => Some(Self::StoredMouseSensorResolutionStage1Y),
            37 => Some(Self::StoredMouseSensorResolutionStage2X),
            38 => Some(Self::StoredMouseSensorResolutionStage2Y),
            39 => Some(Self::StoredMouseSensorResolutionStage3X),
            40 => Some(Self::StoredMouseSensorResolutionStage3Y),
            41 => Some(Self::StoredMouseSensorResolutionStage4X),
            42 => Some(Self::StoredMouseSensorResolutionStage4Y),
            43 => Some(Self::StoredMouseSensorResolutionStage5X),
            44 => Some(Self::StoredMouseSensorResolutionStage5Y),
            45 => Some(Self::StoredMouseSensorResolutionStageSniperX),
            46 => Some(Self::StoredMouseSensorResolutionStageSniperY),
            47 => Some(Self::StoredMouseSensorResolutionStageColor1),
            48 => Some(Self::StoredMouseSensorResolutionStageColor2),
            49 => Some(Self::StoredMouseSensorResolutionStageColor3),
            50 => Some(Self::StoredMouseSensorResolutionStageColor4),
            51 => Some(Self::StoredMouseSensorResolutionStageColor5),
            52 => Some(Self::StoredMouseSensorResolutionStageColorSniper),
            53 => Some(Self::WirelessModeSwitchPosition),
            54 => Some(Self::ConnectedSubdevicesBitmap),
            55 => Some(Self::AutomaticSleepTimeoutPowersave),
            56 => Some(Self::ButtonReleaseDebounceHackTimeout),
            57 => Some(Self::ButtonReleaseDebounceHackEnabled),
            58 => Some(Self::WirelessMode),
            59 => Some(Self::SurfaceCalibrationPresetMode),
            60 => Some(Self::SurfaceCalibrationPresetIndex),
            61 => Some(Self::TotalStorageSize),
            62 => Some(Self::FreeStorageSize),
            63 => Some(Self::MaximumBrightnessLimitEnabled),
            64 => Some(Self::IdleTime),
            65 => Some(Self::PhysicalKeyboardLayout),
            68 => Some(Self::BrightnessLevelIndex),
            69 => Some(Self::WinLockEnabled),
            70 => Some(Self::SidetoneMuted),
            71 => Some(Self::SidetoneLevel),
            73 => Some(Self::ProfileIndicatorColor),
            74 => Some(Self::WinLockDisabledShortcuts),
            75 => Some(Self::WirelessEncryptionStatusSubdevice1),
            79 => Some(Self::HardwareProfile1ActiveMouseSensorResolutionStageIndex),
            80 => Some(Self::HardwareProfile2ActiveMouseSensorResolutionStageIndex),
            81 => Some(Self::HardwareProfile3ActiveMouseSensorResolutionStageIndex),
            82 => Some(Self::AmbidextrousMode),
            85 => Some(Self::CoolerComponentProductLineId),
            86 => Some(Self::CoolerComponentProductVendorId),
            87 => Some(Self::CoolerComponentPumpVersionId),
            88 => Some(Self::CoolerComponentRadiatorSize),
            89 => Some(Self::LedModuleProductLineId),
            90 => Some(Self::LedModuleVendorId),
            91 => Some(Self::LedModuleVersionId),
            92 => Some(Self::BrightnessIndicatorColor),
            93 => Some(Self::WinLockEnabledIndicatorColor),
            94 => Some(Self::WinLockDisabledIndicatorColor),
            95 => Some(Self::WirelessFirmwareVariant),
            96 => Some(Self::DialRingRotation),
            98 => Some(Self::ProfileIndicationBehavior),
            99 => Some(Self::WinLockIndicationBehavior),
            100 => Some(Self::DialModeIndicationBehavior),
            101 => Some(Self::ExceptionalState),
            102 => Some(Self::WirelessEncryptionStatusSubdevice2),
            103 => Some(Self::WirelessEncryptionStatusSubdevice3),
            104 => Some(Self::WirelessEncryptionStatusSubdevice4),
            105 => Some(Self::WirelessEncryptionStatusSubdevice5),
            106 => Some(Self::WirelessEncryptionStatusSubdevice6),
            107 => Some(Self::WirelessEncryptionStatusSubdevice7),
            108 => Some(Self::ActiveDialModeIndex),
            109 => Some(Self::DialZoneBrightness),
            110 => Some(Self::ActiveHardwareProfileIndex),
            115 => Some(Self::WirelessConnectionConfiguration),
            116 => Some(Self::WirelessConnectionConfigurationSupport),
            117 => Some(Self::PrimaryFirmwareStatus),
            118 => Some(Self::EsportsModeSwitchPosition),
            119 => Some(Self::EsportsModeBacklightColor),
            120 => Some(Self::HostOperatingSystem),
            121 => Some(Self::HwDpiAdjustmentEnabled),
            122 => Some(Self::LeftTriggerDeadzone),
            123 => Some(Self::RightTriggerDeadzone),
            124 => Some(Self::LeftThumbstickDeadzone),
            125 => Some(Self::RightThumbstickDeadzone),
            126 => Some(Self::LeftTriggerSensitivity),
            127 => Some(Self::RightTriggerSensitivity),
            128 => Some(Self::LeftThumbstickSensitivity),
            129 => Some(Self::RightThumbstickSensitivity),
            130 => Some(Self::LeftVibrationMotorPresent),
            131 => Some(Self::RightVibrationMotorPresent),
            132 => Some(Self::LeftVibrationMotorIntensity),
            133 => Some(Self::RightVibrationMotorIntensity),
            142 => Some(Self::MicrophoneMuted),
            143 => Some(Self::MicrophoneLevel),
            150 => Some(Self::MaximumPollingRate),
            155 => Some(Self::CapsLockIndicationBehavior),
            156 => Some(Self::ScrollLockIndicationBehavior),
            158 => Some(Self::CapsLockEnabledIndicatorColor),
            159 => Some(Self::ScrollLockEnabledIndicatorColor),
            161 => Some(Self::MacroRecordingIndicatorColor),
            162 => Some(Self::HwMenuFn2SwapFunctionEnabled),
            164 => Some(Self::HardwareProfile4ActiveMouseSensorResolutionStageIndex),
            165 => Some(Self::HardwareProfile5ActiveMouseSensorResolutionStageIndex),
            166 => Some(Self::MicrophoneMuteSwitchPosition),
            168 => Some(Self::GyroscopeReportingMode),
            176 => Some(Self::ButtonDebounceAlgorithm),
            177 => Some(Self::BrightnessIndicationBehavior),
            180 => Some(Self::HardwareActionFeatures),
            183 => Some(Self::TiltForwardGestureTriggerAngle),
            184 => Some(Self::TiltBackwardGestureTriggerAngle),
            185 => Some(Self::TiltLeftGestureTriggerAngle),
            186 => Some(Self::TiltRightGestureTriggerAngle),
            187 => Some(Self::TiltForwardGestureEnabled),
            188 => Some(Self::TiltBackwardGestureEnabled),
            189 => Some(Self::TiltLeftGestureEnabled),
            190 => Some(Self::TiltRightGestureEnabled),
            191 => Some(Self::MultipleGesturesPerMovementEnabled),
            192 => Some(Self::TriggerPositionsReportingEnabled),
            193 => Some(Self::ThumbstickPositionsReportingEnabled),
            196 => Some(Self::AutomaticBrightnessAdjustmentEnabled),
            197 => Some(Self::AutomaticBrightnessOverrideActive),
            198 => Some(Self::AnalogWASDReportingMode),
            199 => Some(Self::AnalogArrowsReportingMode),
            206 => Some(Self::SubdevicesDetectionWarnings),
            _ => None,
        }
    }

    /// Human-readable name for this property (matches the variant name).
    #[must_use]
    pub const fn name(&self) -> &'static str {
        match self {
            Self::Invalid => "Invalid",
            Self::PollingRate => "PollingRate",
            Self::Brightness => "Brightness",
            Self::OperatingMode => "OperatingMode",
            Self::DebugMode => "DebugMode",
            Self::LiftHeight => "LiftHeight",
            Self::AngleSnappingEnabled => "AngleSnappingEnabled",
            Self::AngleSnappingAngle => "AngleSnappingAngle",
            Self::ButtonPressDebounceHackEnabled => "ButtonPressDebounceHackEnabled",
            Self::ButtonPressDebounceHackTimeout => "ButtonPressDebounceHackTimeout",
            Self::PowerSavingModeEnabled => "PowerSavingModeEnabled",
            Self::PowerSavingModeFeatures => "PowerSavingModeFeatures",
            Self::AutomaticSleepEnabled => "AutomaticSleepEnabled",
            Self::AutomaticSleepTimeoutNormal => "AutomaticSleepTimeoutNormal",
            Self::BatteryLevel => "BatteryLevel",
            Self::BatteryStatus => "BatteryStatus",
            Self::UsbVid => "UsbVid",
            Self::UsbPid => "UsbPid",
            Self::FirmwareVersion => "FirmwareVersion",
            Self::BootloaderVersion => "BootloaderVersion",
            Self::WirelessChipFirmwareVersion => "WirelessChipFirmwareVersion",
            Self::WirelessChipBootloaderVersion => "WirelessChipBootloaderVersion",
            Self::RfPower => "RfPower",
            Self::StoredMouseSensorResolutionStage1 => "StoredMouseSensorResolutionStage1",
            Self::StoredMouseSensorResolutionStage2 => "StoredMouseSensorResolutionStage2",
            Self::StoredMouseSensorResolutionStage3 => "StoredMouseSensorResolutionStage3",
            Self::StoredMouseSensorResolutionStage4 => "StoredMouseSensorResolutionStage4",
            Self::StoredMouseSensorResolutionStage5 => "StoredMouseSensorResolutionStage5",
            Self::StoredMouseSensorResolutionStageSniper => "StoredMouseSensorResolutionStageSniper",
            Self::CurrentStoredMouseSensorResolutionStageIndex => "CurrentStoredMouseSensorResolutionStageIndex",
            Self::EnabledStoredMouseSensorResolutionStages => "EnabledStoredMouseSensorResolutionStages",
            Self::MouseSensorResolution => "MouseSensorResolution",
            Self::MouseSensorResolutionX => "MouseSensorResolutionX",
            Self::MouseSensorResolutionY => "MouseSensorResolutionY",
            Self::StoredMouseSensorResolutionStage1X => "StoredMouseSensorResolutionStage1X",
            Self::StoredMouseSensorResolutionStage1Y => "StoredMouseSensorResolutionStage1Y",
            Self::StoredMouseSensorResolutionStage2X => "StoredMouseSensorResolutionStage2X",
            Self::StoredMouseSensorResolutionStage2Y => "StoredMouseSensorResolutionStage2Y",
            Self::StoredMouseSensorResolutionStage3X => "StoredMouseSensorResolutionStage3X",
            Self::StoredMouseSensorResolutionStage3Y => "StoredMouseSensorResolutionStage3Y",
            Self::StoredMouseSensorResolutionStage4X => "StoredMouseSensorResolutionStage4X",
            Self::StoredMouseSensorResolutionStage4Y => "StoredMouseSensorResolutionStage4Y",
            Self::StoredMouseSensorResolutionStage5X => "StoredMouseSensorResolutionStage5X",
            Self::StoredMouseSensorResolutionStage5Y => "StoredMouseSensorResolutionStage5Y",
            Self::StoredMouseSensorResolutionStageSniperX => "StoredMouseSensorResolutionStageSniperX",
            Self::StoredMouseSensorResolutionStageSniperY => "StoredMouseSensorResolutionStageSniperY",
            Self::StoredMouseSensorResolutionStageColor1 => "StoredMouseSensorResolutionStageColor1",
            Self::StoredMouseSensorResolutionStageColor2 => "StoredMouseSensorResolutionStageColor2",
            Self::StoredMouseSensorResolutionStageColor3 => "StoredMouseSensorResolutionStageColor3",
            Self::StoredMouseSensorResolutionStageColor4 => "StoredMouseSensorResolutionStageColor4",
            Self::StoredMouseSensorResolutionStageColor5 => "StoredMouseSensorResolutionStageColor5",
            Self::StoredMouseSensorResolutionStageColorSniper => "StoredMouseSensorResolutionStageColorSniper",
            Self::WirelessModeSwitchPosition => "WirelessModeSwitchPosition",
            Self::ConnectedSubdevicesBitmap => "ConnectedSubdevicesBitmap",
            Self::AutomaticSleepTimeoutPowersave => "AutomaticSleepTimeoutPowersave",
            Self::ButtonReleaseDebounceHackTimeout => "ButtonReleaseDebounceHackTimeout",
            Self::ButtonReleaseDebounceHackEnabled => "ButtonReleaseDebounceHackEnabled",
            Self::WirelessMode => "WirelessMode",
            Self::SurfaceCalibrationPresetMode => "SurfaceCalibrationPresetMode",
            Self::SurfaceCalibrationPresetIndex => "SurfaceCalibrationPresetIndex",
            Self::TotalStorageSize => "TotalStorageSize",
            Self::FreeStorageSize => "FreeStorageSize",
            Self::MaximumBrightnessLimitEnabled => "MaximumBrightnessLimitEnabled",
            Self::IdleTime => "IdleTime",
            Self::PhysicalKeyboardLayout => "PhysicalKeyboardLayout",
            Self::BrightnessLevelIndex => "BrightnessLevelIndex",
            Self::WinLockEnabled => "WinLockEnabled",
            Self::SidetoneMuted => "SidetoneMuted",
            Self::SidetoneLevel => "SidetoneLevel",
            Self::ProfileIndicatorColor => "ProfileIndicatorColor",
            Self::WinLockDisabledShortcuts => "WinLockDisabledShortcuts",
            Self::WirelessEncryptionStatusSubdevice1 => "WirelessEncryptionStatusSubdevice1",
            Self::HardwareProfile1ActiveMouseSensorResolutionStageIndex => "HardwareProfile1ActiveMouseSensorResolutionStageIndex",
            Self::HardwareProfile2ActiveMouseSensorResolutionStageIndex => "HardwareProfile2ActiveMouseSensorResolutionStageIndex",
            Self::HardwareProfile3ActiveMouseSensorResolutionStageIndex => "HardwareProfile3ActiveMouseSensorResolutionStageIndex",
            Self::AmbidextrousMode => "AmbidextrousMode",
            Self::CoolerComponentProductLineId => "CoolerComponentProductLineId",
            Self::CoolerComponentProductVendorId => "CoolerComponentProductVendorId",
            Self::CoolerComponentPumpVersionId => "CoolerComponentPumpVersionId",
            Self::CoolerComponentRadiatorSize => "CoolerComponentRadiatorSize",
            Self::LedModuleProductLineId => "LedModuleProductLineId",
            Self::LedModuleVendorId => "LedModuleVendorId",
            Self::LedModuleVersionId => "LedModuleVersionId",
            Self::BrightnessIndicatorColor => "BrightnessIndicatorColor",
            Self::WinLockEnabledIndicatorColor => "WinLockEnabledIndicatorColor",
            Self::WinLockDisabledIndicatorColor => "WinLockDisabledIndicatorColor",
            Self::WirelessFirmwareVariant => "WirelessFirmwareVariant",
            Self::DialRingRotation => "DialRingRotation",
            Self::ProfileIndicationBehavior => "ProfileIndicationBehavior",
            Self::WinLockIndicationBehavior => "WinLockIndicationBehavior",
            Self::DialModeIndicationBehavior => "DialModeIndicationBehavior",
            Self::ExceptionalState => "ExceptionalState",
            Self::WirelessEncryptionStatusSubdevice2 => "WirelessEncryptionStatusSubdevice2",
            Self::WirelessEncryptionStatusSubdevice3 => "WirelessEncryptionStatusSubdevice3",
            Self::WirelessEncryptionStatusSubdevice4 => "WirelessEncryptionStatusSubdevice4",
            Self::WirelessEncryptionStatusSubdevice5 => "WirelessEncryptionStatusSubdevice5",
            Self::WirelessEncryptionStatusSubdevice6 => "WirelessEncryptionStatusSubdevice6",
            Self::WirelessEncryptionStatusSubdevice7 => "WirelessEncryptionStatusSubdevice7",
            Self::ActiveDialModeIndex => "ActiveDialModeIndex",
            Self::DialZoneBrightness => "DialZoneBrightness",
            Self::ActiveHardwareProfileIndex => "ActiveHardwareProfileIndex",
            Self::WirelessConnectionConfiguration => "WirelessConnectionConfiguration",
            Self::WirelessConnectionConfigurationSupport => "WirelessConnectionConfigurationSupport",
            Self::PrimaryFirmwareStatus => "PrimaryFirmwareStatus",
            Self::EsportsModeSwitchPosition => "EsportsModeSwitchPosition",
            Self::EsportsModeBacklightColor => "EsportsModeBacklightColor",
            Self::HostOperatingSystem => "HostOperatingSystem",
            Self::HwDpiAdjustmentEnabled => "HwDpiAdjustmentEnabled",
            Self::LeftTriggerDeadzone => "LeftTriggerDeadzone",
            Self::RightTriggerDeadzone => "RightTriggerDeadzone",
            Self::LeftThumbstickDeadzone => "LeftThumbstickDeadzone",
            Self::RightThumbstickDeadzone => "RightThumbstickDeadzone",
            Self::LeftTriggerSensitivity => "LeftTriggerSensitivity",
            Self::RightTriggerSensitivity => "RightTriggerSensitivity",
            Self::LeftThumbstickSensitivity => "LeftThumbstickSensitivity",
            Self::RightThumbstickSensitivity => "RightThumbstickSensitivity",
            Self::LeftVibrationMotorPresent => "LeftVibrationMotorPresent",
            Self::RightVibrationMotorPresent => "RightVibrationMotorPresent",
            Self::LeftVibrationMotorIntensity => "LeftVibrationMotorIntensity",
            Self::RightVibrationMotorIntensity => "RightVibrationMotorIntensity",
            Self::MicrophoneMuted => "MicrophoneMuted",
            Self::MicrophoneLevel => "MicrophoneLevel",
            Self::MaximumPollingRate => "MaximumPollingRate",
            Self::CapsLockIndicationBehavior => "CapsLockIndicationBehavior",
            Self::ScrollLockIndicationBehavior => "ScrollLockIndicationBehavior",
            Self::CapsLockEnabledIndicatorColor => "CapsLockEnabledIndicatorColor",
            Self::ScrollLockEnabledIndicatorColor => "ScrollLockEnabledIndicatorColor",
            Self::MacroRecordingIndicatorColor => "MacroRecordingIndicatorColor",
            Self::HwMenuFn2SwapFunctionEnabled => "HwMenuFn2SwapFunctionEnabled",
            Self::HardwareProfile4ActiveMouseSensorResolutionStageIndex => "HardwareProfile4ActiveMouseSensorResolutionStageIndex",
            Self::HardwareProfile5ActiveMouseSensorResolutionStageIndex => "HardwareProfile5ActiveMouseSensorResolutionStageIndex",
            Self::MicrophoneMuteSwitchPosition => "MicrophoneMuteSwitchPosition",
            Self::GyroscopeReportingMode => "GyroscopeReportingMode",
            Self::ButtonDebounceAlgorithm => "ButtonDebounceAlgorithm",
            Self::BrightnessIndicationBehavior => "BrightnessIndicationBehavior",
            Self::HardwareActionFeatures => "HardwareActionFeatures",
            Self::TiltForwardGestureTriggerAngle => "TiltForwardGestureTriggerAngle",
            Self::TiltBackwardGestureTriggerAngle => "TiltBackwardGestureTriggerAngle",
            Self::TiltLeftGestureTriggerAngle => "TiltLeftGestureTriggerAngle",
            Self::TiltRightGestureTriggerAngle => "TiltRightGestureTriggerAngle",
            Self::TiltForwardGestureEnabled => "TiltForwardGestureEnabled",
            Self::TiltBackwardGestureEnabled => "TiltBackwardGestureEnabled",
            Self::TiltLeftGestureEnabled => "TiltLeftGestureEnabled",
            Self::TiltRightGestureEnabled => "TiltRightGestureEnabled",
            Self::MultipleGesturesPerMovementEnabled => "MultipleGesturesPerMovementEnabled",
            Self::TriggerPositionsReportingEnabled => "TriggerPositionsReportingEnabled",
            Self::ThumbstickPositionsReportingEnabled => "ThumbstickPositionsReportingEnabled",
            Self::AutomaticBrightnessAdjustmentEnabled => "AutomaticBrightnessAdjustmentEnabled",
            Self::AutomaticBrightnessOverrideActive => "AutomaticBrightnessOverrideActive",
            Self::AnalogWASDReportingMode => "AnalogWASDReportingMode",
            Self::AnalogArrowsReportingMode => "AnalogArrowsReportingMode",
            Self::SubdevicesDetectionWarnings => "SubdevicesDetectionWarnings",
        }
    }
}

/// Look up the human-readable name for a raw property ID value.
///
/// Returns `None` if the ID is not recognized.
#[must_use]
pub fn property_name(id: u16) -> Option<&'static str> {
    PropertyId::from_u16(id).map(|p| p.name())
}

#[cfg(test)]
#[allow(clippy::unwrap_used)]
mod tests {
    use super::*;

    #[test]
    fn roundtrip_known_ids() {
        let cases: &[(u16, PropertyId)] = &[
            (0, PropertyId::Invalid),
            (1, PropertyId::PollingRate),
            (2, PropertyId::Brightness),
            (15, PropertyId::BatteryLevel),
            (71, PropertyId::SidetoneLevel),
            (143, PropertyId::MicrophoneLevel),
            (206, PropertyId::SubdevicesDetectionWarnings),
        ];
        for &(raw, expected) in cases {
            let decoded = PropertyId::from_u16(raw).unwrap();
            assert_eq!(decoded, expected);
            assert_eq!(decoded as u16, raw);
        }
    }

    #[test]
    fn unknown_id_returns_none() {
        assert!(PropertyId::from_u16(5).is_none());
        assert!(PropertyId::from_u16(999).is_none());
        assert!(PropertyId::from_u16(u16::MAX).is_none());
    }

    #[test]
    fn name_matches_variant() {
        assert_eq!(PropertyId::BatteryLevel.name(), "BatteryLevel");
        assert_eq!(PropertyId::SidetoneLevel.name(), "SidetoneLevel");
    }

    #[test]
    fn property_name_free_fn() {
        assert_eq!(property_name(1), Some("PollingRate"));
        assert_eq!(property_name(5), None);
    }
}
